### ISSUE TITLE
Scambio

### ISSUE THREAD

**Issue by xDonatello** [ElDavoo/TuringOS#3]
Inverti 2° e 3° nastro

**Comment by ElDavoo** [comment]
a che file ti riferisci?

**Comment by xDonatello** [comment]
Nessuno 😂

**Comment by ElDavoo** [comment]
me oh fammi capire

**Comment by xDonatello** [comment]
Semplicemente un pezzo che può tornare utile

**Comment by ElDavoo** [comment]
ah allora scrivi "aggiunta nuovo pezzo", "vorrei avere un pezzo a 3 nastri che scambi i contenuti dei nastri"... in che base?

**Comment by xDonatello** [comment]
Vorrei avere un pezzo in base **decimale** a 3 nastri che scambi il contenuto di 2° e 3° nastro

**Comment by xDonatello** [comment]
Comunque non serve più, me lo ha passato il mitico ripac

**Comment by ElDavoo** [comment]
Non TI serve più, ma è comunque una cosa da aggiungere al repository, quindi riapro.

**Comment by xDonatello** [comment]
> Non TI serve più, ma è comunque una cosa da aggiungere al repository, quindi riapro.

Poi aggiungerò i miei nuovi pezzi quando sarà

**Comment by ElDavoo** [comment]
Fra non chiudere

**Comment by xDonatello** [comment]
> Fra non chiudere

Ma entra l'aria

**Comment by ElDavoo** [comment]
> > Non TI serve più, ma è comunque una cosa da aggiungere al repository, quindi riapro.
> 
> Poi aggiungerò i miei nuovi pezzi quando sarà

li hai aggiunti poi?

**Comment by xDonatello** [comment]
> > > Non TI serve più, ma è comunque una cosa da aggiungere al repository, quindi riapro.
> > 
> > 
> > Poi aggiungerò i miei nuovi pezzi quando sarà
> 
> li hai aggiunti poi?

Si. Puoi chiudere
