### ISSUE TITLE
Aggiunta tracce settembre

### ISSUE THREAD

**Issue by vodibe** [ElDavoo/TuringOS#8]
Quarto e quinto appello dell'anno accademico 2021-2022. Credo che queste siano le ultime 2 tracce di Pani visto che dall'anno accademico 2022-2023 ci sarà un altro docente di calcolabilità
[testo.txt](https://github.com/ElDavoo/TuringOS/files/9623990/testo.txt)
[2022-09-01 + Stringhe.pdf](https://github.com/ElDavoo/TuringOS/files/9623992/2022-09-01.%2B.Stringhe.pdf)
[2022-09-21 + Stringhe.pdf](https://github.com/ElDavoo/TuringOS/files/9623993/2022-09-21.%2B.Stringhe.pdf)

**Comment by ElDavoo** [comment]
Thanks, la prossima volta prova a fare una [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by vodibe** [comment]
va bene, provai in occasione delle tracce di luglio a fare una pull request ma si verificò un errore di autorizzazione, prossima volta riprovo
